[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kunal Kumar", email = "189279211+Kiritostack@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
